# Generated by Django 6.0.1 on 2026-02-01 12:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_benhvien_vi_tri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhvien',
            name='vi_tri',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
