# Generated by Django 6.0.1 on 2026-02-03 02:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_benhnhan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacsi',
            name='ho_ten',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Tên phải có ít nhất một chữ cái.', regex='.*[A-Za-zÀ-ỹ].*')]),
        ),
        migrations.AlterField(
            model_name='bacsi',
            name='so_dien_thoai',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm 9-15 chữ số.', regex='^\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='ho_ten',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Tên phải có ít nhất một chữ cái.', regex='.*[A-Za-zÀ-ỹ].*')]),
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='so_dien_thoai',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm 9-15 chữ số.', regex='^\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='ten',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Tên phải có ít nhất một chữ cái.', regex='.*[A-Za-zÀ-ỹ].*')]),
        ),
        migrations.AlterField(
            model_name='khoa',
            name='ten',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Tên phải có ít nhất một chữ cái.', regex='.*[A-Za-zÀ-ỹ].*')]),
        ),
        migrations.AddConstraint(
            model_name='bacsi',
            constraint=models.UniqueConstraint(fields=('so_dien_thoai',), name='bacsi_so_dien_thoai_unique'),
        ),
        migrations.AddConstraint(
            model_name='baohiemyte',
            constraint=models.CheckConstraint(check=models.Q(('ngay_cap__lte', models.F('ngay_het_han'))), name='bhyt_ngay_cap_lte_ngay_het_han'),
        ),
        migrations.AddConstraint(
            model_name='benhnhan',
            constraint=models.UniqueConstraint(fields=('so_dien_thoai',), name='benhnhan_so_dien_thoai_unique'),
        ),
        migrations.AddConstraint(
            model_name='benhvien',
            constraint=models.CheckConstraint(check=models.Q(('gio_mo__lt', models.F('gio_dong'))), name='benhvien_gio_mo_lt_gio_dong'),
        ),
        migrations.AddConstraint(
            model_name='benhvien',
            constraint=models.CheckConstraint(check=models.Q(('cap_cuu_24h', False), ('co_cap_cuu', True), _connector='OR'), name='benhvien_cap_cuu_24h_requires_cap_cuu'),
        ),
        migrations.AddConstraint(
            model_name='giolamviecbacsi',
            constraint=models.CheckConstraint(check=models.Q(('nghi', True), ('gio_bat_dau__lt', models.F('gio_ket_thuc')), _connector='OR'), name='giolamviec_bacsi_gio_bat_dau_lt_gio_ket_thuc'),
        ),
        migrations.AddConstraint(
            model_name='giolamviecbenhvien',
            constraint=models.CheckConstraint(check=models.Q(('nghi', True), ('gio_mo__lt', models.F('gio_dong')), _connector='OR'), name='giolamviec_benhvien_gio_mo_lt_gio_dong'),
        ),
        migrations.AddConstraint(
            model_name='lichkham',
            constraint=models.UniqueConstraint(fields=('benh_nhan', 'ngay_kham', 'gio_kham'), name='lichkham_benhnhan_ngay_gio_unique'),
        ),
        migrations.AddConstraint(
            model_name='lichkham',
            constraint=models.UniqueConstraint(fields=('benh_nhan', 'ngay_kham'), name='lichkham_benhnhan_ngay_unique'),
        ),
    ]
