# Generated by Django 6.0.1 on 2026-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_lichkham_lichkham_benhnhan_ngay_gio_unique_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='benhvien',
            name='core_benhvi_quan_1986dc_idx',
        ),
        migrations.RenameField(
            model_name='benhvien',
            old_name='quan',
            new_name='phuong',
        ),
        migrations.AddIndex(
            model_name='benhvien',
            index=models.Index(fields=['phuong', 'co_cap_cuu'], name='core_benhvi_phuong_9bc8d2_idx'),
        ),
    ]
