# Generated by Django 5.2.1 on 2026-03-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bacsi_id_alter_baohiemyte_id_alter_benhnhan_id_and_more'),
        ('core', '0010_remove_benhvien_core_benhvi_quan_1986dc_idx_and_more'),
    ]

    operations = [
    ]
