# Generated by Django 6.0.1 on 2026-03-30 07:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_benhvien_core_benhvi_quan_1986dc_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='benhvien',
            constraint=models.CheckConstraint(check=django.db.models.expressions.RawSQL('ST_X(vi_tri) BETWEEN -180 AND 180 AND ST_Y(vi_tri) BETWEEN -90 AND 90', [], output_field=models.BooleanField()), name='benhvien_vi_tri_wgs84_range'),
        ),
    ]
