# Generated by Django 6.0.1 on 2026-03-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bacsi_id_alter_baohiemyte_id_alter_benhnhan_id_and_more'),
        ('core', '0011_benhvien_benhvien_vi_tri_wgs84_range'),
    ]

    operations = [
    ]
