# Generated by Django 6.0.1 on 2026-04-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_phieukhamhinhanh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phieukhamhinhanh',
            options={'ordering': ['thu_tu', 'id'], 'verbose_name': 'Hình ảnh phiếu khám', 'verbose_name_plural': 'Hình ảnh phiếu khám'},
        ),
    ]
