# Generated by Django 5.2.1 on 2026-04-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260329_1713'),
        ('core', '0016_alter_phieukhamhinhanh_options'),
    ]

    operations = [
    ]
