# Generated by Django 6.0.1 on 2026-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_phieukhamhinhanh_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lichkham",
            constraint=models.UniqueConstraint(
                condition=~models.Q(trang_thai="huy"),
                fields=("benh_nhan", "ngay_kham"),
                name="lichkham_benhnhan_ngay_active_unique",
            ),
        ),
    ]
