# Generated by Django 6.0.1 on 2026-04-18 15:40

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_lichkham_benhnhan_ngay_active_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baohiemyte",
            name="ma_bhyt",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    RegexValidator(
                        message="Mã BHYT phải gồm 2 chữ cái và 8 chữ số (ví dụ: AB12345678).",
                        regex="^[A-Za-z]{2}\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.RemoveConstraint(
            model_name="baohiemyte",
            name="bhyt_ngay_cap_lte_ngay_het_han",
        ),
        migrations.AddConstraint(
            model_name="baohiemyte",
            constraint=models.CheckConstraint(check=models.Q(ngay_cap__lt=models.F("ngay_het_han")),
                name="bhyt_ngay_cap_lt_ngay_het_han",
            ),
        ),
    ]
