# Generated by Django 6.0.1 on 2026-04-18 17:40

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_update_bhyt_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bacsi",
            name="so_dien_thoai",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    RegexValidator(
                        message="Số điện thoại phải gồm đúng 10 chữ số và bắt đầu bằng số 0.",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="benhnhan",
            name="so_dien_thoai",
            field=models.CharField(
                db_index=True,
                max_length=15,
                unique=True,
                validators=[
                    RegexValidator(
                        message="Số điện thoại phải gồm đúng 10 chữ số và bắt đầu bằng số 0.",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
        ),
    ]
