# Generated by Django 5.2.1 on 2026-05-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260412_1608'),
        ('core', '0019_alter_bacsi_so_dien_thoai_and_more'),
    ]

    operations = [
    ]
