# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_noidunggioithieu"),
    ]

    operations = [
        migrations.AddField(
            model_name="noidunggioithieu",
            name="anh_banner",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
        migrations.AddField(
            model_name="noidunggioithieu",
            name="hien_ban_do",
            field=models.BooleanField(default=True),
        ),
    ]
