# Generated by Django 6.0.1 on 2026-07-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_noidunggioithieu_anh_banner_hien_ban_do'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lichkham',
            name='lichkham_benhnhan_ngay_gio_active_unique',
        ),
    ]
