# Generated by Django 4.2.13 on 2026-07-04 13:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_lichkham_lichkham_benhnhan_ngay_gio_active_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'administrative_regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'administrative_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GisProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gis_server_id', models.CharField(blank=True, max_length=50, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'gis_provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GisWard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gis_server_id', models.CharField(blank=True, max_length=50, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'gis_wards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wards',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='benhvien',
            name='phuong_xa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
    ]
