# Generated by Django 4.2.13 on 2026-07-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_administrativeregion_administrativeunit_gisprovince_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhnhan',
            name='phuong_xa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
    ]
