# Generated by Django 4.2.13 on 2026-07-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_benhnhan_phuong_xa_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='phuong_xa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benh_nhan_set', to='core.ward'),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='phuong_xa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benh_vien_set', to='core.ward'),
        ),
    ]
