# Generated by Django 6.0.1 on 2026-01-31 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('quan', models.CharField(max_length=100)),
                ('vi_tri', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('co_cap_cuu', models.BooleanField(default=False)),
                ('co_bhyt', models.BooleanField(default=False)),
                ('gio_mo', models.TimeField()),
                ('gio_dong', models.TimeField()),
                ('loai_hinh', models.CharField(choices=[('cong', 'Công'), ('tu', 'Tư'), ('qt', 'Quốc tế')], max_length=10)),
            ],
        ),
    ]
