# Generated by Django 6.0.1 on 2026-02-01 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(db_index=True, max_length=255)),
                ('chuyen_khoa', models.CharField(db_index=True, max_length=200)),
                ('so_dien_thoai', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Bác sĩ',
                'verbose_name_plural': 'Bác sĩ',
            },
        ),
        migrations.CreateModel(
            name='BaoHiemYTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bhyt', models.CharField(max_length=50, unique=True)),
                ('ngay_cap', models.DateField()),
                ('ngay_het_han', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Bảo hiểm y tế',
                'verbose_name_plural': 'Bảo hiểm y tế',
            },
        ),
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(db_index=True, max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=10)),
                ('so_dien_thoai', models.CharField(db_index=True, max_length=15)),
                ('dia_chi', models.TextField()),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Bệnh nhân',
            },
        ),
        migrations.CreateModel(
            name='GioLamViecBacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(0, 'Chủ nhật'), (1, 'Thứ 2'), (2, 'Thứ 3'), (3, 'Thứ 4'), (4, 'Thứ 5'), (5, 'Thứ 6'), (6, 'Thứ 7')], db_index=True)),
                ('gio_bat_dau', models.TimeField()),
                ('gio_ket_thuc', models.TimeField()),
                ('nghi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Giờ làm việc bác sĩ',
                'verbose_name_plural': 'Giờ làm việc bác sĩ',
                'ordering': ['bac_si', 'thu'],
            },
        ),
        migrations.CreateModel(
            name='GioLamViecBenhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(0, 'Chủ nhật'), (1, 'Thứ 2'), (2, 'Thứ 3'), (3, 'Thứ 4'), (4, 'Thứ 5'), (5, 'Thứ 6'), (6, 'Thứ 7')], db_index=True)),
                ('gio_mo', models.TimeField()),
                ('gio_dong', models.TimeField()),
                ('nghi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Giờ làm việc bệnh viện',
                'verbose_name_plural': 'Giờ làm việc bệnh viện',
                'ordering': ['benh_vien', 'thu'],
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Khoa',
            },
        ),
        migrations.CreateModel(
            name='LichKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField(db_index=True)),
                ('gio_kham', models.TimeField()),
                ('trang_thai', models.CharField(choices=[('cho', 'Chờ khám'), ('dang', 'Đang khám'), ('xong', 'Đã xong'), ('huy', 'Đã hủy')], db_index=True, default='cho', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, default='')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch khám',
                'verbose_name_plural': 'Lịch khám',
                'ordering': ['-ngay_kham', '-gio_kham'],
            },
        ),
        migrations.CreateModel(
            name='LichSuKhamBenh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField(db_index=True)),
                ('trieu_chung', models.TextField()),
                ('chan_doan', models.TextField()),
                ('huong_dieu_tri', models.TextField()),
                ('ghi_chu', models.TextField(blank=True, default='')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lịch sử khám bệnh',
                'verbose_name_plural': 'Lịch sử khám bệnh',
                'ordering': ['-ngay_kham', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='LogHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(db_index=True)),
                ('hanh_dong', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa')], db_index=True, max_length=50)),
                ('du_lieu_cu', models.JSONField(blank=True, null=True)),
                ('du_lieu_moi', models.JSONField(blank=True, null=True)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Log hệ thống',
                'verbose_name_plural': 'Log hệ thống',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='LogLichKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(choices=[('tao_moi', 'Tạo mới'), ('cap_nhat', 'Cập nhật'), ('doi_trang_thai', 'Đổi trạng thái'), ('huy', 'Hủy lịch'), ('hoan_thanh', 'Hoàn thành')], db_index=True, max_length=50)),
                ('trang_thai_cu', models.CharField(blank=True, default='', max_length=20)),
                ('trang_thai_moi', models.CharField(blank=True, default='', max_length=20)),
                ('mo_ta', models.TextField(blank=True, default='')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log lịch khám',
                'verbose_name_plural': 'Log lịch khám',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='PhieuKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trieu_chung', models.TextField()),
                ('chan_doan', models.TextField()),
                ('huong_dieu_tri', models.TextField()),
                ('ngay_lap', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Phiếu khám',
                'verbose_name_plural': 'Phiếu khám',
                'ordering': ['-ngay_lap'],
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('lich_kham', 'Lịch khám'), ('phieu_kham', 'Phiếu khám'), ('he_thong', 'Hệ thống'), ('nhac_nho', 'Nhắc nhở')], db_index=True, default='he_thong', max_length=50)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('lien_ket', models.CharField(blank=True, default='', max_length=500)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('da_doc', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.AlterModelOptions(
            name='benhvien',
            options={'verbose_name': 'Bệnh viện', 'verbose_name_plural': 'Bệnh viện'},
        ),
        migrations.AddField(
            model_name='benhvien',
            name='cap_cuu_24h',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='co_bhyt',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='co_cap_cuu',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='loai_hinh',
            field=models.CharField(choices=[('cong', 'Công'), ('tu', 'Tư'), ('qt', 'Quốc tế')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='quan',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='benhvien',
            name='ten',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='benhvien',
            index=models.Index(fields=['quan', 'co_cap_cuu'], name='core_benhvi_quan_1986dc_idx'),
        ),
        migrations.AddIndex(
            model_name='benhvien',
            index=models.Index(fields=['loai_hinh', 'co_bhyt'], name='core_benhvi_loai_hi_1592f1_idx'),
        ),
        migrations.AddIndex(
            model_name='benhvien',
            index=models.Index(fields=['cap_cuu_24h', 'co_cap_cuu'], name='core_benhvi_cap_cuu_26ce8e_idx'),
        ),
        migrations.AddField(
            model_name='bacsi',
            name='benh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_sis', to='core.benhvien'),
        ),
        migrations.AddField(
            model_name='bacsi',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bac_si', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='bhyt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benh_nhan', to='core.baohiemyte'),
        ),
        migrations.AddField(
            model_name='giolamviecbacsi',
            name='bac_si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_lam_viecs', to='core.bacsi'),
        ),
        migrations.AddField(
            model_name='giolamviecbenhvien',
            name='benh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_lam_viecs', to='core.benhvien'),
        ),
        migrations.AddField(
            model_name='khoa',
            name='benh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khoas', to='core.benhvien'),
        ),
        migrations.AddField(
            model_name='bacsi',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_sis', to='core.khoa'),
        ),
        migrations.AddField(
            model_name='lichkham',
            name='bac_si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_khams', to='core.bacsi'),
        ),
        migrations.AddField(
            model_name='lichkham',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_khams', to='core.benhnhan'),
        ),
        migrations.AddField(
            model_name='lichsukhambenh',
            name='bac_si',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_khams', to='core.bacsi'),
        ),
        migrations.AddField(
            model_name='lichsukhambenh',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_khams', to='core.benhnhan'),
        ),
        migrations.AddField(
            model_name='lichsukhambenh',
            name='benh_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_khams', to='core.benhvien'),
        ),
        migrations.AddField(
            model_name='loghethong',
            name='nguoi_thuc_hien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_he_thongs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loglichkham',
            name='lich_kham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.lichkham'),
        ),
        migrations.AddField(
            model_name='loglichkham',
            name='nguoi_thuc_hien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_lich_khams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phieukham',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_khams', to='core.benhnhan'),
        ),
        migrations.AddField(
            model_name='phieukham',
            name='lich_kham',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_kham', to='core.lichkham'),
        ),
        migrations.AddField(
            model_name='lichsukhambenh',
            name='phieu_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_sus', to='core.phieukham'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='nguoi_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thong_baos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='giolamviecbacsi',
            unique_together={('bac_si', 'thu')},
        ),
        migrations.AlterUniqueTogether(
            name='giolamviecbenhvien',
            unique_together={('benh_vien', 'thu')},
        ),
        migrations.AlterUniqueTogether(
            name='khoa',
            unique_together={('ten', 'benh_vien')},
        ),
        migrations.AddIndex(
            model_name='bacsi',
            index=models.Index(fields=['benh_vien', 'chuyen_khoa'], name='core_bacsi_benh_vi_001881_idx'),
        ),
        migrations.AddIndex(
            model_name='lichkham',
            index=models.Index(fields=['bac_si', 'ngay_kham', 'trang_thai'], name='core_lichkh_bac_si__81ff45_idx'),
        ),
        migrations.AddIndex(
            model_name='lichkham',
            index=models.Index(fields=['benh_nhan', 'ngay_kham'], name='core_lichkh_benh_nh_63f874_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lichkham',
            unique_together={('bac_si', 'ngay_kham', 'gio_kham')},
        ),
        migrations.AddIndex(
            model_name='loghethong',
            index=models.Index(fields=['model_name', 'object_id', '-thoi_gian'], name='core_loghet_model_n_3ba39b_idx'),
        ),
        migrations.AddIndex(
            model_name='loghethong',
            index=models.Index(fields=['nguoi_thuc_hien', '-thoi_gian'], name='core_loghet_nguoi_t_27648b_idx'),
        ),
        migrations.AddIndex(
            model_name='loghethong',
            index=models.Index(fields=['hanh_dong', '-thoi_gian'], name='core_loghet_hanh_do_d1ec13_idx'),
        ),
        migrations.AddIndex(
            model_name='loglichkham',
            index=models.Index(fields=['lich_kham', '-thoi_gian'], name='core_loglic_lich_kh_c2d63c_idx'),
        ),
        migrations.AddIndex(
            model_name='loglichkham',
            index=models.Index(fields=['nguoi_thuc_hien', '-thoi_gian'], name='core_loglic_nguoi_t_d519d2_idx'),
        ),
        migrations.AddIndex(
            model_name='loglichkham',
            index=models.Index(fields=['hanh_dong', '-thoi_gian'], name='core_loglic_hanh_do_2f18e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsukhambenh',
            index=models.Index(fields=['benh_nhan', '-ngay_kham'], name='core_lichsu_benh_nh_ee276a_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsukhambenh',
            index=models.Index(fields=['bac_si', '-ngay_kham'], name='core_lichsu_bac_si__641cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsukhambenh',
            index=models.Index(fields=['benh_vien', '-ngay_kham'], name='core_lichsu_benh_vi_90728d_idx'),
        ),
        migrations.AddIndex(
            model_name='thongbao',
            index=models.Index(fields=['nguoi_nhan', 'da_doc', '-thoi_gian'], name='core_thongb_nguoi_n_f30226_idx'),
        ),
        migrations.AddIndex(
            model_name='thongbao',
            index=models.Index(fields=['loai', '-thoi_gian'], name='core_thongb_loai_166c83_idx'),
        ),
    ]
