# Generated by Django 6.0.1 on 2026-02-01 12:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bacsi_baohiemyte_benhnhan_giolamviecbacsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhvien',
            name='vi_tri',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
