# Generated by Django 6.0.1 on 2026-02-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bacsi_ho_ten_alter_bacsi_so_dien_thoai_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lichkham',
            name='lichkham_benhnhan_ngay_unique',
        ),
    ]
