# Generated by Django 6.0.1 on 2026-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_lichkham_lichkham_benhnhan_ngay_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lichkham',
            name='lichkham_benhnhan_ngay_gio_unique',
        ),
        migrations.AlterUniqueTogether(
            name='lichkham',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lichkham',
            constraint=models.UniqueConstraint(condition=models.Q(('trang_thai', 'huy'), _negated=True), fields=('benh_nhan', 'ngay_kham', 'gio_kham'), name='lichkham_benhnhan_ngay_gio_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='lichkham',
            constraint=models.UniqueConstraint(condition=models.Q(('trang_thai', 'huy'), _negated=True), fields=('bac_si', 'ngay_kham', 'gio_kham'), name='lichkham_bacsi_ngay_gio_active_unique'),
        ),
    ]
