# Generated by Django 6.0.1 on 2026-03-30 07:50

import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260330_1447'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benhvien',
            name='benhvien_vi_tri_wgs84_range',
        ),
        migrations.AddConstraint(
            model_name='benhvien',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThanOrEqual(models.Func(models.F('vi_tri'), function='ST_X'), models.Value(-180)), django.db.models.lookups.LessThanOrEqual(models.Func(models.F('vi_tri'), function='ST_X'), models.Value(180)), django.db.models.lookups.GreaterThanOrEqual(models.Func(models.F('vi_tri'), function='ST_Y'), models.Value(-90)), django.db.models.lookups.LessThanOrEqual(models.Func(models.F('vi_tri'), function='ST_Y'), models.Value(90))), name='benhvien_vi_tri_wgs84_range'),
        ),
    ]
