# Generated by Django 6.0.1 on 2026-04-10 06:25

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_benhvien_benhvien_vi_tri_wgs84_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhVienHinhAnh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to=core.models.benh_vien_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('mo_ta', models.CharField(blank=True, default='', max_length=255)),
                ('thu_tu', models.PositiveIntegerField(default=0)),
                ('la_anh_dai_dien', models.BooleanField(db_index=True, default=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('benh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anhs', to='core.benhvien')),
            ],
            options={
                'verbose_name': 'Hình ảnh bệnh viện',
                'verbose_name_plural': 'Hình ảnh bệnh viện',
                'ordering': ['-la_anh_dai_dien', 'thu_tu', 'id'],
                'indexes': [models.Index(fields=['benh_vien', 'thu_tu'], name='core_benhvi_benh_vi_6956dc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('la_anh_dai_dien', True)), fields=('benh_vien',), name='benhvien_single_cover_image')],
            },
        ),
    ]
