# Generated by Django 6.0.1 on 2026-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_phieukhamhinhanh_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benhvien',
            name='benhvien_cap_cuu_24h_requires_cap_cuu',
        ),
        migrations.RemoveIndex(
            model_name='benhvien',
            name='core_benhvi_cap_cuu_26ce8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='benhvien',
            name='core_benhvi_phuong_9bc8d2_idx',
        ),
        migrations.AddIndex(
            model_name='benhvien',
            index=models.Index(fields=['phuong', 'cap_cuu_24h'], name='core_benhvi_phuong_70e0cd_idx'),
        ),
        migrations.RemoveField(
            model_name='benhvien',
            name='co_cap_cuu',
        ),
    ]
