# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_benhvien_benhvien_cap_cuu_24h_requires_cap_cuu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoiDungGioiThieu",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tieu_de_trang", models.CharField(default="Hệ thống tra cứu và đặt lịch khám bệnh tích hợp GIS", max_length=255)),
                ("nut_lien_he", models.CharField(default="Liên hệ", max_length=100)),
                ("nut_kham_pha", models.CharField(default="Khám phá ngay", max_length=100)),
                ("tieu_de_gioi_thieu", models.CharField(default="Giới thiệu hệ thống", max_length=255)),
                ("noi_dung_gioi_thieu", models.TextField(default="Đây là nền tảng web tra cứu bệnh viện và đặt lịch khám trực tuyến, được xây dựng theo định hướng gắn dữ liệu y tế với bản đồ số.")),
                ("tieu_de_van_de", models.CharField(default="Vấn đề & mục tiêu", max_length=255)),
                ("noi_dung_van_de", models.TextField(default="Mục tiêu của đề tài là xây dựng hệ thống trực quan hóa vị trí bệnh viện bằng GIS, hỗ trợ tìm kiếm theo nhiều tiêu chí và cung cấp công cụ ước lượng khoảng cách.")),
                ("tieu_de_chuc_nang", models.CharField(default="Chức năng chính", max_length=255)),
                ("ds_chuc_nang", models.TextField(default="Tra cứu bệnh viện theo từ khóa, phường, loại hình, BHYT, trạng thái hoạt động.\nXem chi tiết bệnh viện: địa chỉ, giờ làm việc, khoa, bác sĩ, hình ảnh.\nĐịnh vị vị trí người dùng và so sánh khoảng cách tới bệnh viện.\nTìm tuyến đường tới bệnh viện và hiển thị quãng đường, thời gian dự kiến.\nĐặt lịch khám trực tuyến và theo dõi lịch khám theo tài khoản.", help_text="Mỗi dòng là một chức năng.")),
                ("tieu_de_gis", models.CharField(default="Thành phần GIS", max_length=255)),
                ("ds_thanh_phan_gis", models.TextField(default="Hiển thị bản đồ và marker bệnh viện bằng Leaflet.\nLưu và xử lý tọa độ bệnh viện bằng PointField (PostGIS).\nTính khoảng cách từ vị trí người dùng bằng hàm Distance của GeoDjango.\nTìm đường đi bằng dịch vụ OSRM để ước lượng quãng đường và thời gian.", help_text="Mỗi dòng là một thành phần GIS.")),
                ("tieu_de_cong_nghe", models.CharField(default="Công nghệ sử dụng", max_length=255)),
                ("ds_cong_nghe", models.TextField(default="Django\nGeoDjango\nPostgreSQL + PostGIS\nLeaflet\nOpenStreetMap\nOSRM\nNominatim\nJavaScript", help_text="Mỗi dòng là một công nghệ.")),
                ("tieu_de_cta", models.CharField(default="Khám phá ngay", max_length=255)),
                ("mo_ta_cta", models.TextField(default="Truy cập trang chủ để trải nghiệm bộ lọc bệnh viện, bản đồ và các chức năng đặt lịch khám.")),
                ("thu_tu", models.PositiveIntegerField(default=1, editable=False, unique=True)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nội dung giới thiệu",
                "verbose_name_plural": "Nội dung giới thiệu",
            },
        ),
    ]
